### ISSUE TITLE
Bluetooth device won't disconnect

### ISSUE THREAD

**Issue by harshilishere** [renanzdm/pos_printer_manager_forked#2]
I noticed when I exit the app by pressing back button several times, the device is still connected to the phone. How to gracefully disconnect the device? maybe we can have some button or something for that?? or maybe we can have like after printing it disconnects automatically?

**Comment by renanzdm** [comment]
inside the bluetooth_printer_manager file on line 119 has the method to disconnect, the disconnection when finished printing I don't find it interesting because I can check if it's already connected and don't need to connect again

**Comment by renanzdm** [comment]
the detach method should only be called if you are connected
